# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_conference_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
