# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_symposium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='themes')),
                ('description', models.TextField(max_length=1000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
            ],
        ),
        migrations.AlterModelOptions(
            name='symposium',
            options={'verbose_name_plural': 'Symposia'},
        ),
        migrations.AlterField(
            model_name='symposium',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='symposia'),
        ),
        migrations.AddField(
            model_name='theme',
            name='symposium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Symposium'),
        ),
    ]
