# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-07 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='SocialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fa', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='sociallink',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.SocialType'),
        ),
    ]
