# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0008_workshop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_delete_greeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('affiliation', models.CharField(max_length=128)),
                ('bio', models.CharField(max_length=140)),
                ('pic', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'profile')),
                ('twitter', models.URLField()),
                ('linkedIn', models.URLField()),
                ('url', models.URLField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
