# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170104_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delegate_type',
            field=models.CharField(choices=[(b'standard', b'Standard'), (b'guest', b'Guest'), (b'committee', b'Committee')], default=b'standard', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
